import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "../utils/ThemeRegistry";
import { SessionProvider } from "../utils/provider";
import { getSession } from "../utils/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <ThemeRegistry options={{ key: "mui-theme" }}>
            {children}
          </ThemeRegistry>
        </body>
      </html>
    </SessionProvider>
  );
}
